from odoo import fields, models


class HrExpense(models.Model):
    _inherit = 'hr.expense'

    cw_shipment_id = fields.Many2one(
        'cw.shipment',
        string='Shipment',
        index=True,
        ondelete='set null',
        copy=False,
        help='Source shipment if this expense was generated from a '
             'freight finalization.',
    )

    cw_freight_category = fields.Selection(
        [
            ('inland_transport', 'Inland Transport'),
            ('export_clearance', 'Export Clearance'),
            ('customs_filing',   'Customs Filing Fee'),
            ('bl_fee',           'BL Fee'),
            ('cert_origin',      'Certificate of Origin'),
            ('documentation',    'Documentation — Other'),
            ('port_fees',        'Port Fees'),
            ('actual_freight',   'Actual Freight'),
        ],
        string='Freight Category',
        index=True,
        copy=False,
        help='Set when this expense is generated by a cw.shipment '
             'freight finalization. Drives BI grouping.',
    )
